language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
env:
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.4
  - DJANGO_VERSION=1.9a1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: python src/runtests.py