language: python
python:
  - 3.9
  - 3.10
env:
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: python src/runtests.py
notifications:
  email:
    on_success: change
    on_failure: change
